version: '3.8'

services:
   mongodb:
      container_name: mongodb
      image: mongo
      env_file: 
         - ../.env
      environment:
         MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ports:
         - "27017:27017"
      volumes:
         - mongo_data:/data/db

   mongo-express:
      image: mongo-express
      env_file: 
         - ../.env
      environment:
         ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
         ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
         ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
         ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
         ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ports:
         - "8081:8081"
      depends_on:
         - mongodb

   backend:
      build:
         context: ..
         dockerfile: dockerfile/Dockerfile.server
      env_file: 
         - ../.env
      environment:
         MONGODB_URI: ${MONGODB_URI}
         JWT_SECRET: ${JWT_SECRET}
         PORT: ${PORT}
      ports:
         - "3001:3001"
      depends_on:
         - mongodb

   frontend:
      build:
         context: ..
         dockerfile: dockerfile/Dockerfile.client
      ports:
         - "3000:80"
      depends_on:
         - backend

volumes:
   mongo_data: