services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: sustainability_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    restart: always

  backend:
    build:
      context: ..
      dockerfile: dockerfile/Dockerfile.server
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/sustainability_db"
      JWT_SECRET: your_secret_key_here
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../client
      dockerfile: ../dockerfile/Dockerfile.client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ../client:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

volumes:
  mongo_data: