FROM node:20-alpine
WORKDIR /app
COPY --chmod=0755 server/package*.json ./
RUN npm install
RUN npm i --save-dev @types/bcryptjs @types/jsonwebtoken typescript
COPY --chmod=0755 server/ .
EXPOSE 3001
CMD ["npm", "start"]
